import type { Domain } from '../../shared/types.js';

export const DOMAINS: Domain[] = [
  {
    id: 'tech-startup',
    name: 'Tech Startup',
    nameHe: 'סטארטאפ טכנולוגי',
    icon: '🚀',
    description: 'Software, apps, AI, SaaS products',
    color: '#6366f1',
    exampleTopics: ['Build an AI-powered CRM', 'SaaS for small businesses', 'Mobile app for fitness tracking'],
  },
  {
    id: 'real-estate',
    name: 'Real Estate',
    nameHe: 'נדל"ן',
    icon: '🏢',
    description: 'Property development, investment, management',
    color: '#0891b2',
    exampleTopics: ['Develop a residential complex', 'PropTech platform', 'Real estate investment fund'],
  },
  {
    id: 'stocks-investments',
    name: 'Stocks & Investments',
    nameHe: 'מניות והשקעות',
    icon: '📈',
    description: 'Stock trading, portfolio management, funds',
    color: '#059669',
    exampleTopics: ['Launch a hedge fund', 'Robo-advisor platform', 'Crypto investment strategy'],
  },
  {
    id: 'ecommerce',
    name: 'E-Commerce',
    nameHe: 'מסחר אלקטרוני',
    icon: '🛒',
    description: 'Online stores, marketplaces, D2C brands',
    color: '#ea580c',
    exampleTopics: ['Launch a D2C fashion brand', 'B2B marketplace', 'Subscription box service'],
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    nameHe: 'בריאות',
    icon: '🏥',
    description: 'MedTech, clinics, health services, pharma',
    color: '#dc2626',
    exampleTopics: ['Telemedicine platform', 'Mental health app', 'Medical device startup'],
  },
  {
    id: 'education',
    name: 'Education',
    nameHe: 'חינוך',
    icon: '📚',
    description: 'EdTech, schools, training, courses',
    color: '#7c3aed',
    exampleTopics: ['Online learning platform', 'Coding bootcamp', 'Corporate training solution'],
  },
  {
    id: 'construction',
    name: 'Construction',
    nameHe: 'בניין',
    icon: '🏗️',
    description: 'Building, infrastructure, engineering',
    color: '#b45309',
    exampleTopics: ['Green building company', 'Construction management software', 'Modular housing startup'],
  },
  {
    id: 'food-restaurant',
    name: 'Restaurant & Food',
    nameHe: 'מסעדנות ומזון',
    icon: '🍽️',
    description: 'Restaurants, food production, FoodTech',
    color: '#be185d',
    exampleTopics: ['Restaurant chain expansion', 'Cloud kitchen concept', 'Plant-based food brand'],
  },
  {
    id: 'legal',
    name: 'Legal Practice',
    nameHe: 'משפטים',
    icon: '⚖️',
    description: 'Law firms, LegalTech, compliance',
    color: '#4f46e5',
    exampleTopics: ['AI contract review tool', 'Boutique law firm', 'Legal marketplace platform'],
  },
  {
    id: 'sports-fitness',
    name: 'Sports & Fitness',
    nameHe: 'ספורט וכושר',
    icon: '⚽',
    description: 'SportsTech, gyms, athletic brands',
    color: '#16a34a',
    exampleTopics: ['Sports analytics platform', 'Boutique gym chain', 'Athlete management app'],
  },
  {
    id: 'agriculture',
    name: 'Agriculture',
    nameHe: 'חקלאות',
    icon: '🌾',
    description: 'AgriTech, farming, food supply chain',
    color: '#65a30d',
    exampleTopics: ['Precision farming platform', 'Vertical farming startup', 'Agricultural drone service'],
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing',
    nameHe: 'תעשייה',
    icon: '🏭',
    description: 'Production, industrial, supply chain',
    color: '#6b7280',
    exampleTopics: ['Smart factory automation', 'Custom manufacturing marketplace', '3D printing service'],
  },
  {
    id: 'entertainment-media',
    name: 'Entertainment & Media',
    nameHe: 'בידור ומדיה',
    icon: '🎬',
    description: 'Content, streaming, gaming, media',
    color: '#e11d48',
    exampleTopics: ['Streaming platform for niche content', 'Interactive storytelling app', 'Podcast network'],
  },
  {
    id: 'energy',
    name: 'Energy & CleanTech',
    nameHe: 'אנרגיה וקלינטק',
    icon: '⚡',
    description: 'Renewable energy, sustainability, green tech',
    color: '#0d9488',
    exampleTopics: ['Solar energy startup', 'EV charging network', 'Carbon credit marketplace'],
  },
  {
    id: 'financial-services',
    name: 'Financial Services',
    nameHe: 'שירותים פיננסיים',
    icon: '🏦',
    description: 'FinTech, banking, insurance, payments',
    color: '#1e40af',
    exampleTopics: ['Neobank for freelancers', 'InsurTech platform', 'Cross-border payment solution'],
  },
  {
    id: 'transportation',
    name: 'Transportation & Logistics',
    nameHe: 'תחבורה ולוגיסטיקה',
    icon: '🚛',
    description: 'Shipping, logistics, mobility, fleet management',
    color: '#0369a1',
    exampleTopics: ['Last-mile delivery optimization', 'Fleet management platform', 'Ride-sharing for rural areas'],
  },
  {
    id: 'fashion-retail',
    name: 'Fashion & Retail',
    nameHe: 'אופנה וקמעונאות',
    icon: '👗',
    description: 'Fashion brands, retail stores, personal styling',
    color: '#a21caf',
    exampleTopics: ['Sustainable fashion brand', 'AI personal stylist', 'Pop-up retail concept'],
  },
  {
    id: 'cybersecurity',
    name: 'Cybersecurity',
    nameHe: 'אבטחת סייבר',
    icon: '🔒',
    description: 'Security products, consulting, threat intelligence',
    color: '#334155',
    exampleTopics: ['SMB security platform', 'Threat intelligence marketplace', 'Security awareness training'],
  },
  {
    id: 'nonprofit',
    name: 'Non-Profit',
    nameHe: 'ארגון ללא מטרות רווח',
    icon: '🤝',
    description: 'NGOs, social impact, charity, community',
    color: '#9333ea',
    exampleTopics: ['Education non-profit', 'Community platform for volunteers', 'Social impact fund'],
  },
  {
    id: 'gaming',
    name: 'Gaming',
    nameHe: 'גיימינג',
    icon: '🎮',
    description: 'Game studios, esports, gaming platforms',
    color: '#7c3aed',
    exampleTopics: ['Mobile game studio', 'Esports tournament platform', 'Game streaming service'],
  },
  {
    id: 'saas',
    name: 'SaaS',
    nameHe: 'תוכנה כשירות',
    icon: '☁️',
    description: 'B2B/B2C software-as-a-service products',
    color: '#2563eb',
    exampleTopics: ['Project management tool', 'HR automation platform', 'Analytics dashboard SaaS'],
  },
  {
    id: 'consulting',
    name: 'Consulting',
    nameHe: 'ייעוץ',
    icon: '💼',
    description: 'Management consulting, strategy, advisory',
    color: '#475569',
    exampleTopics: ['Boutique strategy firm', 'Digital transformation consultancy', 'Fractional C-suite service'],
  },
  {
    id: 'other',
    name: 'Other',
    nameHe: 'אחר',
    icon: '🔮',
    description: 'Any field not listed above — describe your domain',
    color: '#a855f7',
    exampleTopics: ['Describe your unique industry', 'Niche market venture', 'Cross-industry idea'],
  },
];
